export const CATEGORIES = [
  { key: "all", label: "All", emoji: "✨" },
  { key: "cafe", label: "Cafes", emoji: "☕" },
  { key: "restobar", label: "Restobars", emoji: "🍹" },
  { key: "seafood", label: "Seafood", emoji: "🦞" },
  { key: "beach", label: "Beaches", emoji: "🏖️" },
  { key: "hidden_gem", label: "Hidden Gems", emoji: "🌿" },
  { key: "scooter_rental", label: "Scooter Rentals", emoji: "🛵" }
];

export const CATEGORY_EMOJI = {
  cafe: "☕",
  restobar: "🍹",
  seafood: "🦞",
  beach: "🏖️",
  hidden_gem: "🌿",
  scooter_rental: "🛵"
};

export const spots = [
  // CAFES
  { id: 1, name: "Artjuna Café", category: "cafe", area: "Arambol",
    lat: 15.6870, lng: 73.7037, rating: 4.6, reviews: 312,
    priceRange: "₹₹", description: "Boho garden café with organic food and hammocks",
    openNow: true },
  { id: 2, name: "Infantaria Café", category: "cafe", area: "Baga",
    lat: 15.5617, lng: 73.7519, rating: 4.4, reviews: 876,
    priceRange: "₹₹", description: "Iconic Goa bakery café since 1993",
    openNow: true },
  { id: 3, name: "A Reverie", category: "cafe", area: "Panjim",
    lat: 15.4978, lng: 73.8311, rating: 4.6, reviews: 521,
    priceRange: "₹₹", description: "Quirky café with eclectic décor in heritage Fontainhas",
    openNow: true },
  { id: 4, name: "Pousada by the Beach", category: "cafe", area: "Calangute",
    lat: 15.5440, lng: 73.7628, rating: 4.4, reviews: 543,
    priceRange: "₹₹", description: "Charming Portuguese villa café with garden brunch",
    openNow: true },

  // RESTOBARS
  { id: 5, name: "Sublime", category: "restobar", area: "Vagator",
    lat: 15.6027, lng: 73.7351, rating: 4.8, reviews: 891,
    priceRange: "₹₹₹", description: "Award-winning fine dining with cliff views",
    openNow: true },
  { id: 6, name: "Thalassa", category: "restobar", area: "Vagator",
    lat: 15.6018, lng: 73.7344, rating: 4.5, reviews: 1204,
    priceRange: "₹₹₹", description: "Greek restaurant with stunning sunset cliff seating",
    openNow: true },
  { id: 7, name: "Antares", category: "restobar", area: "Vagator",
    lat: 15.6021, lng: 73.7340, rating: 4.7, reviews: 567,
    priceRange: "₹₹₹", description: "Chef Floyd's beach-view restaurant and beach club",
    openNow: true },
  { id: 8, name: "Curlies Beach Shack", category: "restobar", area: "Anjuna",
    lat: 15.5766, lng: 73.7404, rating: 4.2, reviews: 2341,
    priceRange: "₹₹", description: "Legendary Anjuna beach shack and party spot",
    openNow: true },
  { id: 9, name: "Black Sheep Bistro", category: "restobar", area: "Panjim",
    lat: 15.4989, lng: 73.8278, rating: 4.7, reviews: 654,
    priceRange: "₹₹₹", description: "Craft cocktails and innovative Goan cuisine",
    openNow: false },
  { id: 10, name: "Bomra's", category: "restobar", area: "Panjim",
    lat: 15.5004, lng: 73.8267, rating: 4.8, reviews: 432,
    priceRange: "₹₹₹", description: "Burmese fine dining, one of Goa's best kept secrets",
    openNow: false },
  { id: 11, name: "Gunpowder", category: "restobar", area: "Assagao",
    lat: 15.5891, lng: 73.7629, rating: 4.7, reviews: 789,
    priceRange: "₹₹", description: "South Indian cuisine in a beautiful garden setting",
    openNow: true },
  { id: 12, name: "La Plage", category: "restobar", area: "Ashvem",
    lat: 15.6531, lng: 73.7128, rating: 4.6, reviews: 445,
    priceRange: "₹₹₹", description: "French beach restaurant, Goa's most stylish lunch spot",
    openNow: true },

  // SEAFOOD
  { id: 13, name: "Britto's", category: "seafood", area: "Baga",
    lat: 15.5609, lng: 73.7521, rating: 4.3, reviews: 3102,
    priceRange: "₹₹", description: "Famous beachside seafood and live music",
    openNow: true },
  { id: 14, name: "Fisherman's Wharf", category: "seafood", area: "Cavelossim",
    lat: 15.1824, lng: 73.9478, rating: 4.4, reviews: 1876,
    priceRange: "₹₹", description: "Riverside seafood with authentic Goan fish curry",
    openNow: true },
  { id: 15, name: "Mum's Kitchen", category: "seafood", area: "Panjim",
    lat: 15.4956, lng: 73.8289, rating: 4.8, reviews: 1123,
    priceRange: "₹₹", description: "Legendary home-style Goan food, grandma recipes",
    openNow: true },
  { id: 16, name: "Vinayak Family Restaurant", category: "seafood", area: "Margao",
    lat: 15.2832, lng: 73.9862, rating: 4.5, reviews: 2341,
    priceRange: "₹", description: "No-frills local legend for best fish thali in South Goa",
    openNow: true },

  // HIDDEN GEMS
  { id: 17, name: "Sweet Water Lake", category: "hidden_gem", area: "Arambol",
    lat: 15.6891, lng: 73.7021, rating: 4.9, reviews: 234,
    priceRange: "₹", description: "Secret freshwater lake behind Arambol beach, magical at sunset",
    openNow: true },
  { id: 18, name: "Chapora Fort", category: "hidden_gem", area: "Vagator",
    lat: 15.6089, lng: 73.7289, rating: 4.7, reviews: 3421,
    priceRange: "₹", description: "Ancient Portuguese fort, Dil Chahta Hai spot, epic 360° views",
    openNow: true },

  // BEACHES
  { id: 19, name: "Morjim Beach", category: "beach", area: "Morjim",
    lat: 15.6390, lng: 73.7219, rating: 4.5, reviews: 1234,
    priceRange: "₹", description: "Quiet turtle-nesting beach, peaceful, almost no hawkers",
    openNow: true },
  { id: 20, name: "Mandrem Beach", category: "beach", area: "Mandrem",
    lat: 15.6612, lng: 73.7134, rating: 4.8, reviews: 876,
    priceRange: "₹", description: "Goa's most peaceful beach, perfect for yoga and sunsets",
    openNow: true },

  // SCOOTER RENTALS
  { id: 21, name: "Raju Bike Rentals", category: "scooter_rental", area: "Baga",
    lat: 15.5630, lng: 73.7510, rating: 4.3, reviews: 187,
    priceRange: "₹",
    description: "Activa & scooters from ₹300/day. Daily, weekly rates available.",
    openNow: true },
  { id: 22, name: "Morjim Bike Rentals", category: "scooter_rental", area: "Morjim",
    lat: 15.6385, lng: 73.7225, rating: 4.2, reviews: 143,
    priceRange: "₹",
    description: "Scooters from ₹300–500/day depending on model. Right at the beach.",
    openNow: true },
  { id: 23, name: "Palolem Scooter Rentals", category: "scooter_rental", area: "Palolem",
    lat: 15.0100, lng: 74.0230, rating: 4.1, reviews: 98,
    priceRange: "₹",
    description: "South Goa rentals from ₹400–500/day. Good condition bikes.",
    openNow: true }
];
